// Code generated by schemagen from schema/*.cue. DO NOT EDIT.

package registry

import "time"

// InterruptPolicy decides a call's fate on barge-in (SPEC §4.4).
type InterruptPolicy string

const (
	InterruptCancel          InterruptPolicy = "cancel"
	InterruptDetach          InterruptPolicy = "detach"
	InterruptUninterruptible InterruptPolicy = "uninterruptible"
)

// Scope gates invocation by identified speaker (SPEC §5).
type Scope string

const (
	ScopeHousehold Scope = "household"
	ScopePerson    Scope = "person"
	ScopeGuest     Scope = "guest"
)

// ParamSpec is one declared parameter. Providers map these onto their own wire
// shape, so every backend offers the model the same tool (SPEC §12).
type ParamSpec struct {
	Name        string
	Type        string
	Description string
	Required    bool
	Enum        []string
	Items       string
}

// ToolSpec is the generated policy for one tool.
type ToolSpec struct {
	Name        string
	Description string

	// ModelDescription is what the model is told, which is not what the docs
	// show: a slow tool carries a latency hint it has to act on (SPEC §14).
	ModelDescription string

	// Params are what the tool's executor declares and receives. ModelParams
	// are what the model is offered, which adds the arguments the
	// orchestrator acts on and strips before the executor sees the call: the
	// acknowledgement on a slow tool, the nonce on a confirmable one.
	Params               []ParamSpec
	ModelParams          []ParamSpec
	OnInterrupt          InterruptPolicy
	Scope                Scope
	Timeout              time.Duration
	RequiresConfirmation bool
	Slow                 bool
	UnknownSpeaker       string

	// ConfirmWhen holds the calls whose arguments match any entry for the
	// person's yes, when the tool as a whole needs none (ADR-0038).
	ConfirmWhen []ConfirmRule
}

// ConfirmRule is one confirm_when entry. A call matches when its arguments
// carry every value in Args and, when TargetClass names any, what it acts
// on has one of those classes (ADR-0041).
type ConfirmRule struct {
	Args        map[string]string
	TargetClass []string
}

// Specs is every declared tool, keyed by name.
var Specs = map[string]ToolSpec{
	"end_session": {
		Name:                 "end_session",
		Description:          "Close the conversation. Call when the task is complete rather than waiting for silence.",
		ModelDescription:     "Close the conversation. Call when the task is complete rather than waiting for silence.",
		OnInterrupt:          "cancel",
		Scope:                "household",
		Timeout:              10000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 false,
	},
	"forget": {
		Name:             "forget",
		Description:      "Forget something you remember about the person you are speaking with, so it is never recalled again. Name it by the id shown beside it in what you remember.",
		ModelDescription: "Forget something you remember about the person you are speaking with, so it is never recalled again. Name it by the id shown beside it in what you remember.",
		Params: []ParamSpec{
			{Name: "memory_id", Type: "string", Description: "The id of the memory to forget, e.g. m_3f9c2a10.", Required: true},
		},
		ModelParams: []ParamSpec{
			{Name: "memory_id", Type: "string", Description: "The id of the memory to forget, e.g. m_3f9c2a10.", Required: true},
		},
		OnInterrupt:          "cancel",
		Scope:                "person",
		Timeout:              10000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 false,
		UnknownSpeaker:       "deny",
	},
	"ha_call_service": {
		Name:             "ha_call_service",
		Description:      "Act on the home through a Home Assistant service: lights, switches, covers, media players, scripts. Target an entity_id from ha_find_entities, or an area_id. Returns the entities whose state changed; an empty list means nothing matched or nothing needed to change.",
		ModelDescription: "Act on the home through a Home Assistant service: lights, switches, covers, media players, scripts. Target an entity_id from ha_find_entities, or an area_id. Returns the entities whose state changed; an empty list means nothing matched or nothing needed to change. Some calls need the person's yes: they return confirmation_required with a nonce. Ask them, and once they agree, call again with the same arguments and confirmation set to the nonce.",
		Params: []ParamSpec{
			{Name: "domain", Type: "string", Description: "Service domain, e.g. light, switch, script.", Required: true},
			{Name: "service", Type: "string", Description: "Service within the domain, e.g. turn_on, turn_off, toggle.", Required: true},
			{Name: "entity_id", Type: "string", Description: "Entity to act on, e.g. light.kitchen. Required unless area_id is given.", Required: false},
			{Name: "area_id", Type: "string", Description: "Area to act on, e.g. kitchen. Required unless entity_id is given.", Required: false},
			{Name: "data", Type: "object", Description: "Extra service fields, e.g. {\"brightness_pct\": 50}.", Required: false},
		},
		ModelParams: []ParamSpec{
			{Name: "domain", Type: "string", Description: "Service domain, e.g. light, switch, script.", Required: true},
			{Name: "service", Type: "string", Description: "Service within the domain, e.g. turn_on, turn_off, toggle.", Required: true},
			{Name: "entity_id", Type: "string", Description: "Entity to act on, e.g. light.kitchen. Required unless area_id is given.", Required: false},
			{Name: "area_id", Type: "string", Description: "Area to act on, e.g. kitchen. Required unless entity_id is given.", Required: false},
			{Name: "data", Type: "object", Description: "Extra service fields, e.g. {\"brightness_pct\": 50}.", Required: false},
			{Name: "confirmation", Type: "string", Description: "The nonce from a confirmation_required result, once the person has said yes. Omit it otherwise.", Required: false},
		},
		OnInterrupt:          "detach",
		Scope:                "household",
		Timeout:              10000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 false,
		ConfirmWhen: []ConfirmRule{
			{Args: map[string]string{"domain": "lock", "service": "unlock"}},
			{Args: map[string]string{"domain": "lock", "service": "open"}},
			{Args: map[string]string{"domain": "alarm_control_panel", "service": "alarm_disarm"}},
			{Args: map[string]string{"domain": "cover", "service": "open_cover"}, TargetClass: []string{"door", "garage", "gate"}},
			{Args: map[string]string{"domain": "cover", "service": "toggle"}, TargetClass: []string{"door", "garage", "gate"}},
			{Args: map[string]string{"domain": "cover", "service": "set_cover_position"}, TargetClass: []string{"door", "garage", "gate"}},
			{Args: map[string]string{"domain": "homeassistant", "service": "toggle"}, TargetClass: []string{"door", "garage", "gate"}},
		},
	},
	"ha_find_entities": {
		Name:             "ha_find_entities",
		Description:      "Find Home Assistant entities by domain and name. Call this first when you do not know an entity_id; never guess one.",
		ModelDescription: "Find Home Assistant entities by domain and name. Call this first when you do not know an entity_id; never guess one.",
		Params: []ParamSpec{
			{Name: "domain", Type: "string", Description: "Only entities in this domain, e.g. light.", Required: false},
			{Name: "name", Type: "string", Description: "Only entities whose name or id contains this text, e.g. kitchen.", Required: false},
		},
		ModelParams: []ParamSpec{
			{Name: "domain", Type: "string", Description: "Only entities in this domain, e.g. light.", Required: false},
			{Name: "name", Type: "string", Description: "Only entities whose name or id contains this text, e.g. kitchen.", Required: false},
		},
		OnInterrupt:          "cancel",
		Scope:                "household",
		Timeout:              10000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 false,
	},
	"ha_get_state": {
		Name:             "ha_get_state",
		Description:      "Read one entity's current state and attributes from Home Assistant.",
		ModelDescription: "Read one entity's current state and attributes from Home Assistant.",
		Params: []ParamSpec{
			{Name: "entity_id", Type: "string", Description: "Entity to read, e.g. sensor.living_room_temperature.", Required: true},
		},
		ModelParams: []ParamSpec{
			{Name: "entity_id", Type: "string", Description: "Entity to read, e.g. sensor.living_room_temperature.", Required: true},
		},
		OnInterrupt:          "cancel",
		Scope:                "household",
		Timeout:              10000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 false,
	},
	"media_search": {
		Name:             "media_search",
		Description:      "Search the media library.",
		ModelDescription: "Search the media library. Takes several seconds to return.",
		Params: []ParamSpec{
			{Name: "query", Type: "string", Description: "Free-text search.", Required: true},
			{Name: "limit", Type: "integer", Description: "Maximum results.", Required: false},
		},
		ModelParams: []ParamSpec{
			{Name: "query", Type: "string", Description: "Free-text search.", Required: true},
			{Name: "limit", Type: "integer", Description: "Maximum results.", Required: false},
			{Name: "acknowledgement", Type: "string", Description: "A few words said aloud while this runs, e.g. \"Searching the library.\" They are spoken for you as it starts; do not also call speak for them.", Required: true},
		},
		OnInterrupt:          "detach",
		Scope:                "household",
		Timeout:              20000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 true,
	},
	"remember": {
		Name:             "remember",
		Description:      "Keep a lasting fact about the person you are speaking with, to recall in later conversations. Use it when they ask you to remember something, or tell you a preference that will still hold tomorrow.",
		ModelDescription: "Keep a lasting fact about the person you are speaking with, to recall in later conversations. Use it when they ask you to remember something, or tell you a preference that will still hold tomorrow.",
		Params: []ParamSpec{
			{Name: "fact", Type: "string", Description: "The fact, as one plain sentence that makes sense on its own later, e.g. Takes oat milk in coffee.", Required: true},
			{Name: "shareable", Type: "boolean", Description: "True only when they say the rest of the household may know it.", Required: false},
		},
		ModelParams: []ParamSpec{
			{Name: "fact", Type: "string", Description: "The fact, as one plain sentence that makes sense on its own later, e.g. Takes oat milk in coffee.", Required: true},
			{Name: "shareable", Type: "boolean", Description: "True only when they say the rest of the household may know it.", Required: false},
		},
		OnInterrupt:          "cancel",
		Scope:                "person",
		Timeout:              10000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 false,
		UnknownSpeaker:       "deny",
	},
	"speak": {
		Name:             "speak",
		Description:      "Say something to the user. Runs concurrently with other tools; the model chooses when and whether to speak.",
		ModelDescription: "Say something to the user. Runs concurrently with other tools; the model chooses when and whether to speak.",
		Params: []ParamSpec{
			{Name: "text", Type: "string", Description: "What to say.", Required: true},
			{Name: "mode", Type: "string", Description: "queue appends after current speech; preempt cancels it; interject ducks and cuts in.", Required: false, Enum: []string{"queue", "preempt", "interject"}},
		},
		ModelParams: []ParamSpec{
			{Name: "text", Type: "string", Description: "What to say.", Required: true},
			{Name: "mode", Type: "string", Description: "queue appends after current speech; preempt cancels it; interject ducks and cuts in.", Required: false, Enum: []string{"queue", "preempt", "interject"}},
		},
		OnInterrupt:          "cancel",
		Scope:                "household",
		Timeout:              10000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 false,
	},
}
