// Code generated by schemagen from schema/*.cue. DO NOT EDIT.

package registry

import "time"

// InterruptPolicy decides a call's fate on barge-in (SPEC §4.4).
type InterruptPolicy string

const (
	InterruptCancel          InterruptPolicy = "cancel"
	InterruptDetach          InterruptPolicy = "detach"
	InterruptUninterruptible InterruptPolicy = "uninterruptible"
)

// Scope gates invocation by identified speaker (SPEC §5).
type Scope string

const (
	ScopeHousehold Scope = "household"
	ScopePerson    Scope = "person"
	ScopeGuest     Scope = "guest"
)

// ToolSpec is the generated policy for one tool.
type ToolSpec struct {
	Name                 string
	Description          string
	OnInterrupt          InterruptPolicy
	Scope                Scope
	Timeout              time.Duration
	RequiresConfirmation bool
	Slow                 bool
	UnknownSpeaker       string
}

// Specs is every declared tool, keyed by name.
var Specs = map[string]ToolSpec{
	"end_session": {
		Name:                 "end_session",
		Description:          "Close the conversation. Call when the task is complete rather than waiting for silence.",
		OnInterrupt:          "cancel",
		Scope:                "household",
		Timeout:              10000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 false,
	},
	"media_search": {
		Name:                 "media_search",
		Description:          "Search the media library.",
		OnInterrupt:          "detach",
		Scope:                "household",
		Timeout:              20000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 true,
	},
	"remember": {
		Name:                 "remember",
		Description:          "Store a durable fact about the current speaker.",
		OnInterrupt:          "cancel",
		Scope:                "person",
		Timeout:              10000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 false,
		UnknownSpeaker:       "deny",
	},
	"speak": {
		Name:                 "speak",
		Description:          "Say something to the user. Runs concurrently with other tools; the model chooses when and whether to speak.",
		OnInterrupt:          "cancel",
		Scope:                "household",
		Timeout:              10000 * time.Millisecond,
		RequiresConfirmation: false,
		Slow:                 false,
	},
}
