// Code generated by schemagen from schema/*.cue. DO NOT EDIT.

package journal

// Kind identifies a journal event type. The journal is the source of truth,
// so every write is validated against this set (SPEC §8).
type Kind string

// Actor is the supervisor child that produced an event (SPEC §4).
type Actor string

const (
	// Interruption passed the detection gate. Timing is milliseconds into TTS playback, not wall clock, so replay reproduces the cut.
	KindBargeInDetected Kind = "barge_in_detected"
	// Candidate interruption failed the detection gate. Tuning corpus for SPEC §4.3.
	KindBargeInRejected Kind = "barge_in_rejected"
	// Model finished a completion. Recorded in full, not just the request, because replay cannot regenerate it (SPEC §8).
	KindModelCompleted Kind = "model_completed"
	// Conversation ended.
	KindSessionClosed Kind = "session_closed"
	// Wake word confirmed; a conversation begins.
	KindSessionOpened Kind = "session_opened"
	// Audio the user actually heard, bounded by DAC-reported playback position.
	KindSpeechSpoken Kind = "speech_spoken"
	// Barge-in cut speech short. Carries the exact split between heard and unheard text.
	KindSpeechTruncated Kind = "speech_truncated"
	// Model dispatched a tool; emitted when its JSON closed, not at end of message.
	KindToolCalled Kind = "tool_called"
	// Tool completed, failed, or timed out. Failures are results the model reasons about (SPEC §7).
	KindToolResult Kind = "tool_result"
	// Final STT result for one utterance.
	KindUtteranceTranscribed Kind = "utterance_transcribed"
	// Stage-one activation failed server-side confirmation. Hard negative for wake-word retraining.
	KindWakeRejected Kind = "wake_rejected"
)

// EventMeta is generated metadata used by the journal and the harvester.
type EventMeta struct {
	Actor            Actor
	HasAudio         bool
	TrainingSignal   bool
	Speculative      bool
	RequiresVersions bool
	RequiredFields   []string
}

// Meta describes every known event kind.
var Meta = map[Kind]EventMeta{
	KindBargeInDetected:      {Actor: "listening", HasAudio: true, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"tts_position_ms"}},
	KindBargeInRejected:      {Actor: "listening", HasAudio: true, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"stage"}},
	KindModelCompleted:       {Actor: "thinking", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: true, RequiredFields: []string{"completion_json", "finish_reason"}},
	KindSessionClosed:        {Actor: "session", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"reason"}},
	KindSessionOpened:        {Actor: "session", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"satellite"}},
	KindSpeechSpoken:         {Actor: "speaking", HasAudio: true, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"text", "frames_played"}},
	KindSpeechTruncated:      {Actor: "speaking", HasAudio: true, TrainingSignal: true, Speculative: false, RequiresVersions: true, RequiredFields: []string{"spoken_text", "unspoken_text", "frames_played"}},
	KindToolCalled:           {Actor: "thinking", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"tool", "call_id", "args_json"}},
	KindToolResult:           {Actor: "tool", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"call_id", "outcome"}},
	KindUtteranceTranscribed: {Actor: "listening", HasAudio: true, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"text"}},
	KindWakeRejected:         {Actor: "device", HasAudio: true, TrainingSignal: true, Speculative: false, RequiresVersions: true, RequiredFields: []string{"reason"}},
}

// AllKinds lets replay assert exhaustive handling.
var AllKinds = []Kind{
	KindBargeInDetected,
	KindBargeInRejected,
	KindModelCompleted,
	KindSessionClosed,
	KindSessionOpened,
	KindSpeechSpoken,
	KindSpeechTruncated,
	KindToolCalled,
	KindToolResult,
	KindUtteranceTranscribed,
	KindWakeRejected,
}
