// Code generated by schemagen from schema/*.cue. DO NOT EDIT.

package journal

// Kind identifies a journal event type. The journal is the source of truth,
// so every write is validated against this set (SPEC §8).
type Kind string

// Actor is the supervisor child that produced an event (SPEC §4).
type Actor string

const (
	// Something was said that nobody in this conversation asked for: a timer going off, or someone in another room asking for it to be said here. Recorded in the conversation it was said in, ahead of the speak call that says it (SPEC §4).
	KindAnnouncementMade Kind = "announcement_made"
	// Interruption passed the detection gate. Timing is milliseconds into TTS playback, not wall clock, so replay reproduces the cut.
	KindBargeInDetected Kind = "barge_in_detected"
	// Candidate interruption failed the detection gate. Tuning corpus for SPEC §4.3.
	KindBargeInRejected Kind = "barge_in_rejected"
	// A held call came back with its nonce after the person answered, and ran. What they said is the utterance the nonce was redeemed after (SPEC §6).
	KindConfirmationGiven Kind = "confirmation_given"
	// A call that needs the person's yes was held, and the model was handed a nonce to call again with once they agree (SPEC §6).
	KindConfirmationRequested Kind = "confirmation_requested"
	// The conversation ended and the model summarized it for the identified people in it, to be told in their later conversations. Recorded in full, as a completion is, because replay cannot regenerate it (SPEC §5, §8).
	KindConversationSummarized Kind = "conversation_summarized"
	// What the model is told it remembers, from this turn on: the speaker's own memories and what others shared, and their recent conversations, chosen by relevance when there are more than fit. Recorded when it changes, so a replay asks the model with what it was given (SPEC §5).
	KindMemoryRecalled Kind = "memory_recalled"
	// Model finished a completion. Recorded in full, not just the request, because replay cannot regenerate it (SPEC §8).
	KindModelCompleted Kind = "model_completed"
	// The model could not answer the turn: it was unreachable, its stream broke, or it went quiet past its deadline. No model is left to reason with, so a canned line says so instead (SPEC §7, ADR-0051).
	KindModelFailed Kind = "model_failed"
	// The satellite's own presence sensor changed: the Satellite1's mmWave radar, read over the native API. Recorded in the device's log, since presence belongs to the room, not to a conversation (ADR-0050).
	KindPresenceChanged Kind = "presence_changed"
	// Session ended. The conversation outlives it when the reason is a migration: the person moved device, so this session closes and a resumed one opens (SPEC §4.5). An announcement nobody was asked to answer closes as announced once it has been said.
	KindSessionClosed Kind = "session_closed"
	// Wake word confirmed; a session begins. A resumed one joins a conversation already in progress on another device (SPEC §4.5).
	KindSessionOpened Kind = "session_opened"
	// Speech generated but never played, because a barge-in, or whatever reason names, emptied the queue first. Distinct from truncation: nothing was heard.
	KindSpeechDiscarded Kind = "speech_discarded"
	// A speak call's audio failed short of the person interrupting: the voice could not render it, or the device never confirmed playing it. The truncation or discard it caused names the same reason, so it is never mistaken for a barge-in (SPEC §7, ADR-0051).
	KindSpeechFailed Kind = "speech_failed"
	// Audio the user actually heard, bounded by DAC-reported playback position.
	KindSpeechSpoken Kind = "speech_spoken"
	// The DAC played the first frame of a turn's speech. Recorded once per turn, when the device reports it, so its wall clock is when the household first heard the answer (SPEC §11).
	KindSpeechStarted Kind = "speech_started"
	// Speech was cut short, usually by a barge-in; reason says what cut it. Carries the exact split between heard and unheard text.
	KindSpeechTruncated Kind = "speech_truncated"
	// A running timer was cancelled before it went off.
	KindTimerCancelled Kind = "timer_cancelled"
	// A timer went off, and whether anybody was told. A timer nobody heard is a failure the household felt, so it is recorded as one (SPEC §7).
	KindTimerFinished Kind = "timer_finished"
	// A timer was set. Recorded in the household's own log, which the daemon replays at startup to know what is running, so a timer outlives the session that set it and the process (ADR-0045).
	KindTimerStarted Kind = "timer_started"
	// Model dispatched a tool; emitted when its JSON closed, not at end of message.
	KindToolCalled Kind = "tool_called"
	// Tool completed, failed, or timed out. Failures are results the model reasons about (SPEC §7).
	KindToolResult Kind = "tool_result"
	// Final STT result for one utterance.
	KindUtteranceTranscribed Kind = "utterance_transcribed"
	// Stage-one activation failed server-side confirmation. Hard negative for wake-word retraining.
	KindWakeRejected Kind = "wake_rejected"
)

// EventMeta is generated metadata used by the journal and the harvester.
type EventMeta struct {
	Actor            Actor
	HasAudio         bool
	TrainingSignal   bool
	Speculative      bool
	RequiresVersions bool
	RequiredFields   []string
}

// Meta describes every known event kind.
var Meta = map[Kind]EventMeta{
	KindAnnouncementMade:       {Actor: "session", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"text", "call_id", "source"}},
	KindBargeInDetected:        {Actor: "listening", HasAudio: true, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"tts_position_ms"}},
	KindBargeInRejected:        {Actor: "listening", HasAudio: true, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"stage"}},
	KindConfirmationGiven:      {Actor: "session", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"call_id", "nonce"}},
	KindConfirmationRequested:  {Actor: "session", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"call_id", "nonce"}},
	KindConversationSummarized: {Actor: "session", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: true, RequiredFields: []string{"people_json"}},
	KindMemoryRecalled:         {Actor: "session", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"memories_json"}},
	KindModelCompleted:         {Actor: "thinking", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: true, RequiredFields: []string{"completion_json", "finish_reason"}},
	KindModelFailed:            {Actor: "thinking", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: true, RequiredFields: []string{"reason", "error"}},
	KindPresenceChanged:        {Actor: "device", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"state"}},
	KindSessionClosed:          {Actor: "session", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"reason", "satellite"}},
	KindSessionOpened:          {Actor: "session", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"satellite"}},
	KindSpeechDiscarded:        {Actor: "speaking", HasAudio: false, TrainingSignal: true, Speculative: false, RequiresVersions: true, RequiredFields: []string{"unspoken_text", "reason"}},
	KindSpeechFailed:           {Actor: "speaking", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"call_id", "reason"}},
	KindSpeechSpoken:           {Actor: "speaking", HasAudio: true, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"text", "frames_played"}},
	KindSpeechStarted:          {Actor: "speaking", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"call_id"}},
	KindSpeechTruncated:        {Actor: "speaking", HasAudio: true, TrainingSignal: true, Speculative: false, RequiresVersions: true, RequiredFields: []string{"spoken_text", "unspoken_text", "frames_played"}},
	KindTimerCancelled:         {Actor: "tool", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"timer_id", "conversation_id", "call_id"}},
	KindTimerFinished:          {Actor: "session", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"timer_id", "outcome"}},
	KindTimerStarted:           {Actor: "tool", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"timer_id", "seconds", "fires_at", "satellite", "conversation_id", "call_id"}},
	KindToolCalled:             {Actor: "thinking", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"tool", "call_id", "args_json"}},
	KindToolResult:             {Actor: "tool", HasAudio: false, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"call_id", "outcome"}},
	KindUtteranceTranscribed:   {Actor: "listening", HasAudio: true, TrainingSignal: false, Speculative: false, RequiresVersions: false, RequiredFields: []string{"text"}},
	KindWakeRejected:           {Actor: "device", HasAudio: true, TrainingSignal: true, Speculative: false, RequiresVersions: true, RequiredFields: []string{"reason"}},
}

// AllKinds lets replay assert exhaustive handling.
var AllKinds = []Kind{
	KindAnnouncementMade,
	KindBargeInDetected,
	KindBargeInRejected,
	KindConfirmationGiven,
	KindConfirmationRequested,
	KindConversationSummarized,
	KindMemoryRecalled,
	KindModelCompleted,
	KindModelFailed,
	KindPresenceChanged,
	KindSessionClosed,
	KindSessionOpened,
	KindSpeechDiscarded,
	KindSpeechFailed,
	KindSpeechSpoken,
	KindSpeechStarted,
	KindSpeechTruncated,
	KindTimerCancelled,
	KindTimerFinished,
	KindTimerStarted,
	KindToolCalled,
	KindToolResult,
	KindUtteranceTranscribed,
	KindWakeRejected,
}
