// Command schemagen turns CUE schemas into Go types, LLM-facing JSON Schema,
// and reference docs. One declaration drives the model's view of a tool and the
// orchestrator's enforcement of it, so the two cannot drift (SPEC §6).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const header = "// Code generated by schemagen from schema/*.cue. DO NOT EDIT.\n\n"

type Param struct {
	Name        string   `json:"name"`
	Type        string   `json:"type"`
	Description string   `json:"description"`
	Required    bool     `json:"required"`
	Enum        []string `json:"enum,omitempty"`
	Items       string   `json:"items,omitempty"`
}

type Tool struct {
	Name                 string  `json:"name"`
	Description          string  `json:"description"`
	Params               []Param `json:"params"`
	OnInterrupt          string  `json:"on_interrupt"`
	Scope                string  `json:"scope"`
	TimeoutMS            int     `json:"timeout_ms"`
	RequiresConfirmation bool    `json:"requires_confirmation"`
	Latency              string  `json:"latency"`
	UnknownSpeaker       string  `json:"unknown_speaker,omitempty"`
}

type Event struct {
	Name            string  `json:"name"`
	Actor           string  `json:"actor"`
	Description     string  `json:"description"`
	Speculative     bool    `json:"speculative"`
	HasAudio        bool    `json:"has_audio"`
	TrainingSignal  bool    `json:"training_signal"`
	RequiresVersion bool    `json:"requires_versions"`
	Fields          []Param `json:"fields"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "schemagen: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	var tools map[string]Tool
	if err := cueExport("tools", &tools); err != nil {
		return err
	}
	var events map[string]Event
	if err := cueExport("events", &events); err != nil {
		return err
	}
	if len(tools) == 0 || len(events) == 0 {
		return fmt.Errorf("schema produced no tools (%d) or events (%d)", len(tools), len(events))
	}

	writes := map[string][]byte{
		"internal/registry/tools.gen.go": []byte(renderToolsGo(tools)),
		"internal/journal/events.gen.go": []byte(renderEventsGo(events)),
		"schema/json/tools.schema.json":  mustJSON(LLMToolSchemas(tools)),
		"docs/reference/tools.md":        []byte(renderToolDocs(tools)),
		"docs/reference/events.md":       []byte(renderEventDocs(events)),
	}
	for path, content := range writes {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		fmt.Println("  wrote", path)
	}
	return gofmt(writes)
}

func cueExport(expr string, into any) error {
	cmd := exec.Command("cue", "export", "./schema/", "-e", expr)
	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("cue export -e %s: %w", expr, err)
	}
	return json.Unmarshal(out, into)
}

func gofmt(writes map[string][]byte) error {
	var goFiles []string
	for p := range writes {
		if strings.HasSuffix(p, ".go") {
			goFiles = append(goFiles, p)
		}
	}
	sort.Strings(goFiles)
	return exec.Command("gofmt", append([]string{"-w"}, goFiles...)...).Run()
}

func mustJSON(v any) []byte {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		panic(err)
	}
	return append(b, '\n')
}

// ------------------------------------------------------------- pure renderers

// LLMToolSchemas builds the model-facing tool definitions. This is the same
// declaration the orchestrator enforces policy from, which is the point.
func LLMToolSchemas(tools map[string]Tool) []map[string]any {
	out := make([]map[string]any, 0, len(tools))
	for _, key := range sortedKeys(tools) {
		t := tools[key]
		props := map[string]any{}
		var required []string
		for _, p := range t.Params {
			prop := map[string]any{"type": p.Type, "description": p.Description}
			if len(p.Enum) > 0 {
				prop["enum"] = p.Enum
			}
			if p.Items != "" {
				prop["items"] = map[string]any{"type": p.Items}
			}
			props[p.Name] = prop
			if p.Required {
				required = append(required, p.Name)
			}
		}
		schema := map[string]any{"type": "object", "properties": props}
		if len(required) > 0 {
			schema["required"] = required
		}
		out = append(out, map[string]any{
			"name":         t.Name,
			"description":  describe(t),
			"input_schema": schema,
		})
	}
	return out
}

// slowHint is appended to a slow tool's model-facing description. Measured, not
// assumed: with it, qwen3:14b and ornith:9b volunteer a `speak` alongside the
// slow call; without it both call the tool alone and leave the user in silence.
// The latency field is the registry's own, so the hint cannot drift from the
// timeout policy generated beside it (SPEC §6, §14).
const slowHint = " Takes several seconds to return."

// describe is the tool description the model sees, which is not quite the one
// the docs show: latency is policy the model has to act on, not just metadata.
func describe(t Tool) string {
	if t.Latency != "slow" {
		return t.Description
	}
	return t.Description + slowHint
}

func renderToolsGo(tools map[string]Tool) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package registry\n\nimport \"time\"\n\n")

	b.WriteString(`// InterruptPolicy decides a call's fate on barge-in (SPEC §4.4).
type InterruptPolicy string

const (
	InterruptCancel          InterruptPolicy = "cancel"
	InterruptDetach          InterruptPolicy = "detach"
	InterruptUninterruptible InterruptPolicy = "uninterruptible"
)

// Scope gates invocation by identified speaker (SPEC §5).
type Scope string

const (
	ScopeHousehold Scope = "household"
	ScopePerson    Scope = "person"
	ScopeGuest     Scope = "guest"
)

// ParamSpec is one declared parameter. Providers map these onto their own wire
// shape, so every backend offers the model the same tool (SPEC §12).
type ParamSpec struct {
	Name        string
	Type        string
	Description string
	Required    bool
	Enum        []string
	Items       string
}

// ToolSpec is the generated policy for one tool.
type ToolSpec struct {
	Name        string
	Description string

	// ModelDescription is what the model is told, which is not what the docs
	// show: a slow tool carries a latency hint it has to act on (SPEC §14).
	ModelDescription string

	Params               []ParamSpec
	OnInterrupt          InterruptPolicy
	Scope                Scope
	Timeout              time.Duration
	RequiresConfirmation bool
	Slow                 bool
	UnknownSpeaker       string
}

`)
	b.WriteString("// Specs is every declared tool, keyed by name.\nvar Specs = map[string]ToolSpec{\n")
	for _, key := range sortedKeys(tools) {
		t := tools[key]
		b.WriteString(fmt.Sprintf("\t%q: {\n", t.Name))
		b.WriteString(fmt.Sprintf("\t\tName: %q,\n", t.Name))
		b.WriteString(fmt.Sprintf("\t\tDescription: %q,\n", t.Description))
		b.WriteString(fmt.Sprintf("\t\tModelDescription: %q,\n", describe(t)))
		b.WriteString(renderParams(t.Params))
		b.WriteString(fmt.Sprintf("\t\tOnInterrupt: %q,\n", t.OnInterrupt))
		b.WriteString(fmt.Sprintf("\t\tScope: %q,\n", t.Scope))
		b.WriteString(fmt.Sprintf("\t\tTimeout: %d * time.Millisecond,\n", t.TimeoutMS))
		b.WriteString(fmt.Sprintf("\t\tRequiresConfirmation: %t,\n", t.RequiresConfirmation))
		b.WriteString(fmt.Sprintf("\t\tSlow: %t,\n", t.Latency == "slow"))
		if t.UnknownSpeaker != "" {
			b.WriteString(fmt.Sprintf("\t\tUnknownSpeaker: %q,\n", t.UnknownSpeaker))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func renderParams(params []Param) string {
	if len(params) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("\t\tParams: []ParamSpec{\n")
	for _, p := range params {
		b.WriteString(fmt.Sprintf("\t\t\t{Name: %q, Type: %q, Description: %q, Required: %t",
			p.Name, p.Type, p.Description, p.Required))
		if len(p.Enum) > 0 {
			quoted := make([]string, len(p.Enum))
			for i, e := range p.Enum {
				quoted[i] = fmt.Sprintf("%q", e)
			}
			b.WriteString(fmt.Sprintf(", Enum: []string{%s}", strings.Join(quoted, ", ")))
		}
		if p.Items != "" {
			b.WriteString(fmt.Sprintf(", Items: %q", p.Items))
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t\t},\n")
	return b.String()
}

func renderEventsGo(events map[string]Event) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package journal\n\n")
	b.WriteString(`// Kind identifies a journal event type. The journal is the source of truth,
// so every write is validated against this set (SPEC §8).
type Kind string

// Actor is the supervisor child that produced an event (SPEC §4).
type Actor string

`)
	b.WriteString("const (\n")
	for _, key := range sortedKeys(events) {
		e := events[key]
		b.WriteString(fmt.Sprintf("\t// %s\n", e.Description))
		b.WriteString(fmt.Sprintf("\tKind%s Kind = %q\n", goName(e.Name), e.Name))
	}
	b.WriteString(")\n\n")

	b.WriteString("// EventMeta is generated metadata used by the journal and the harvester.\ntype EventMeta struct {\n\tActor Actor\n\tHasAudio bool\n\tTrainingSignal bool\n\tSpeculative bool\n\tRequiresVersions bool\n\tRequiredFields []string\n}\n\n")
	b.WriteString("// Meta describes every known event kind.\nvar Meta = map[Kind]EventMeta{\n")
	for _, key := range sortedKeys(events) {
		e := events[key]
		var req []string
		for _, f := range e.Fields {
			if f.Required {
				req = append(req, fmt.Sprintf("%q", f.Name))
			}
		}
		b.WriteString(fmt.Sprintf("\tKind%s: {Actor: %q, HasAudio: %t, TrainingSignal: %t, Speculative: %t, RequiresVersions: %t, RequiredFields: []string{%s}},\n",
			goName(e.Name), e.Actor, e.HasAudio, e.TrainingSignal, e.Speculative, e.RequiresVersion, strings.Join(req, ", ")))
	}
	b.WriteString("}\n\n")

	b.WriteString("// AllKinds lets replay assert exhaustive handling.\nvar AllKinds = []Kind{\n")
	for _, key := range sortedKeys(events) {
		b.WriteString(fmt.Sprintf("\tKind%s,\n", goName(events[key].Name)))
	}
	b.WriteString("}\n")
	return b.String()
}

func renderToolDocs(tools map[string]Tool) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by schemagen from schema/tool.cue. DO NOT EDIT. -->\n\n")
	b.WriteString("# Tool registry reference\n\nSee [SPEC §6](../SPEC.md). Policy is enforced by the orchestrator from these same declarations.\n\n")
	b.WriteString("| Tool | Interrupt | Scope | Timeout | Confirm | Latency |\n|---|---|---|---|---|---|\n")
	for _, key := range sortedKeys(tools) {
		t := tools[key]
		confirm := "no"
		if t.RequiresConfirmation {
			confirm = "**yes**"
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %dms | %s | %s |\n",
			t.Name, t.OnInterrupt, t.Scope, t.TimeoutMS, confirm, t.Latency))
	}
	b.WriteString("\n")
	for _, key := range sortedKeys(tools) {
		t := tools[key]
		b.WriteString(fmt.Sprintf("## `%s`\n\n%s\n\n", t.Name, t.Description))
		if t.UnknownSpeaker != "" {
			b.WriteString(fmt.Sprintf("Unknown speaker: `%s`.\n\n", t.UnknownSpeaker))
		}
		if len(t.Params) == 0 {
			b.WriteString("No parameters.\n\n")
			continue
		}
		b.WriteString("| Parameter | Type | Required | Description |\n|---|---|---|---|\n")
		for _, p := range t.Params {
			req := ""
			if p.Required {
				req = "yes"
			}
			desc := p.Description
			if len(p.Enum) > 0 {
				desc += fmt.Sprintf(" One of: `%s`.", strings.Join(p.Enum, "`, `"))
			}
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", p.Name, p.Type, req, desc))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderEventDocs(events map[string]Event) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by schemagen from schema/event.cue. DO NOT EDIT. -->\n\n")
	b.WriteString("# Event taxonomy reference\n\nSee [SPEC §8](../SPEC.md). The journal is the runtime's source of truth.\n\n")
	b.WriteString("| Event | Actor | Audio | Training signal | Description |\n|---|---|---|---|---|\n")
	for _, key := range sortedKeys(events) {
		e := events[key]
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s |\n",
			e.Name, e.Actor, yn(e.HasAudio), yn(e.TrainingSignal), e.Description))
	}
	return b.String()
}

func yn(b bool) string {
	if b {
		return "yes"
	}
	return ""
}

func goName(s string) string {
	var b strings.Builder
	for part := range strings.SplitSeq(strings.ReplaceAll(s, ".", "_"), "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
