// Command schemagen turns CUE schemas into Go types, LLM-facing JSON Schema,
// and reference docs. One declaration drives the model's view of a tool and the
// orchestrator's enforcement of it, so the two cannot drift (SPEC §6).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const header = "// Code generated by schemagen from schema/*.cue. DO NOT EDIT.\n\n"

type Param struct {
	Name        string   `json:"name"`
	Type        string   `json:"type"`
	Description string   `json:"description"`
	Required    bool     `json:"required"`
	Enum        []string `json:"enum,omitempty"`
	Items       string   `json:"items,omitempty"`
}

type Tool struct {
	Name                 string  `json:"name"`
	Description          string  `json:"description"`
	Params               []Param `json:"params"`
	OnInterrupt          string  `json:"on_interrupt"`
	Scope                string  `json:"scope"`
	TimeoutMS            int     `json:"timeout_ms"`
	RequiresConfirmation bool    `json:"requires_confirmation"`
	Latency              string  `json:"latency"`
	UnknownSpeaker       string  `json:"unknown_speaker,omitempty"`

	ConfirmWhen []ConfirmRule `json:"confirm_when,omitempty"`
}

// targetClassKey names the classes in a confirm_when entry; every other key
// is a string parameter.
const targetClassKey = "target_class"

// ConfirmRule is one confirm_when entry, split into the arguments it matches
// and the classes of target it holds (ADR-0041).
type ConfirmRule struct {
	Args        map[string]string
	TargetClass []string
}

func (r *ConfirmRule) UnmarshalJSON(b []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(b, &raw); err != nil {
		return fmt.Errorf("confirm_when entry: %w", err)
	}
	r.Args = map[string]string{}
	for k, v := range raw {
		if k == targetClassKey {
			if err := json.Unmarshal(v, &r.TargetClass); err != nil {
				return fmt.Errorf("confirm_when %s: %w", k, err)
			}
			continue
		}
		var arg string
		if err := json.Unmarshal(v, &arg); err != nil {
			return fmt.Errorf("confirm_when %s: %w", k, err)
		}
		r.Args[k] = arg
	}
	return nil
}

type Event struct {
	Name            string  `json:"name"`
	Actor           string  `json:"actor"`
	Description     string  `json:"description"`
	Speculative     bool    `json:"speculative"`
	HasAudio        bool    `json:"has_audio"`
	TrainingSignal  bool    `json:"training_signal"`
	RequiresVersion bool    `json:"requires_versions"`
	Fields          []Param `json:"fields"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "schemagen: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	var tools map[string]Tool
	if err := cueExport("tools", &tools); err != nil {
		return err
	}
	var events map[string]Event
	if err := cueExport("events", &events); err != nil {
		return err
	}
	if len(tools) == 0 || len(events) == 0 {
		return fmt.Errorf("schema produced no tools (%d) or events (%d)", len(tools), len(events))
	}

	writes := map[string][]byte{
		"internal/registry/tools.gen.go": []byte(renderToolsGo(tools)),
		"internal/journal/events.gen.go": []byte(renderEventsGo(events)),
		"schema/json/tools.schema.json":  mustJSON(LLMToolSchemas(tools)),
		"docs/reference/tools.md":        []byte(renderToolDocs(tools)),
		"docs/reference/events.md":       []byte(renderEventDocs(events)),
	}
	for path, content := range writes {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		fmt.Println("  wrote", path)
	}
	return gofmt(writes)
}

func cueExport(expr string, into any) error {
	cmd := exec.Command("cue", "export", "./schema/", "-e", expr)
	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("cue export -e %s: %w", expr, err)
	}
	return json.Unmarshal(out, into)
}

func gofmt(writes map[string][]byte) error {
	var goFiles []string
	for p := range writes {
		if strings.HasSuffix(p, ".go") {
			goFiles = append(goFiles, p)
		}
	}
	sort.Strings(goFiles)
	return exec.Command("gofmt", append([]string{"-w"}, goFiles...)...).Run()
}

func mustJSON(v any) []byte {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		panic(err)
	}
	return append(b, '\n')
}

// ------------------------------------------------------------- pure renderers

// LLMToolSchemas builds the model-facing tool definitions. This is the same
// declaration the orchestrator enforces policy from, which is the point.
func LLMToolSchemas(tools map[string]Tool) []map[string]any {
	out := make([]map[string]any, 0, len(tools))
	for _, key := range sortedKeys(tools) {
		t := tools[key]
		props := map[string]any{}
		var required []string
		for _, p := range offered(t) {
			prop := map[string]any{"type": p.Type, "description": p.Description}
			if len(p.Enum) > 0 {
				prop["enum"] = p.Enum
			}
			if p.Items != "" {
				prop["items"] = map[string]any{"type": p.Items}
			}
			props[p.Name] = prop
			if p.Required {
				required = append(required, p.Name)
			}
		}
		schema := map[string]any{"type": "object", "properties": props}
		if len(required) > 0 {
			schema["required"] = required
		}
		out = append(out, map[string]any{
			"name":         t.Name,
			"description":  describe(t),
			"input_schema": schema,
		})
	}
	return out
}

// slowHint is appended to a slow tool's model-facing description. The
// latency field is the registry's own, so the hint cannot drift from the
// timeout policy generated beside it (SPEC §6, §14).
const slowHint = " Takes several seconds to return."

// ackParam is required on every slow tool: the words said aloud while it
// works. The orchestrator speaks them as the call starts, so an
// acknowledgement no longer depends on the model volunteering a speak call
// beside the tool, which measured models do some of the time and not
// others (ADR-0039). Spelled as registry.AcknowledgementParam.
var ackParam = Param{
	Name:        "acknowledgement",
	Type:        "string",
	Description: "A few words said aloud while this runs, e.g. \"Searching the library.\" They are spoken for you as it starts; do not also call speak for them.",
	Required:    true,
}

// confirmParam carries a confirmed call's nonce. Spelled as
// registry.ConfirmationParam, which this generator cannot import: it writes
// that package.
var confirmParam = Param{
	Name:        "confirmation",
	Type:        "string",
	Description: "The nonce from a confirmation_required result, once the person has said yes. Omit it otherwise.",
}

// Hints for a confirmable tool: the model has to know a held call is not a
// failure, and how to finish it (SPEC §6, ADR-0038).
const (
	confirmAllHint  = " Every call needs the person's yes: it returns confirmation_required with a nonce. Ask them, and once they agree, call again with the same arguments and confirmation set to the nonce."
	confirmSomeHint = " Some calls need the person's yes: they return confirmation_required with a nonce. Ask them, and once they agree, call again with the same arguments and confirmation set to the nonce."
)

// confirmable reports whether any call to the tool can be held for the
// person's yes.
func confirmable(t Tool) bool { return t.RequiresConfirmation || len(t.ConfirmWhen) > 0 }

// offered is the parameters the model is offered: the declared ones, the
// acknowledgement on a slow tool, and the nonce on a confirmable one.
func offered(t Tool) []Param {
	out := append([]Param(nil), t.Params...)
	if t.Latency == "slow" {
		out = append(out, ackParam)
	}
	if confirmable(t) {
		out = append(out, confirmParam)
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// describe is the tool description the model sees, which is not quite the one
// the docs show: latency and confirmation are policy the model has to act
// on, not just metadata.
func describe(t Tool) string {
	d := t.Description
	if t.Latency == "slow" {
		d += slowHint
	}
	switch {
	case t.RequiresConfirmation:
		d += confirmAllHint
	case len(t.ConfirmWhen) > 0:
		d += confirmSomeHint
	}
	return d
}

func renderToolsGo(tools map[string]Tool) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package registry\n\nimport \"time\"\n\n")

	b.WriteString(`// InterruptPolicy decides a call's fate on barge-in (SPEC §4.4).
type InterruptPolicy string

const (
	InterruptCancel          InterruptPolicy = "cancel"
	InterruptDetach          InterruptPolicy = "detach"
	InterruptUninterruptible InterruptPolicy = "uninterruptible"
)

// Scope gates invocation by identified speaker (SPEC §5).
type Scope string

const (
	ScopeHousehold Scope = "household"
	ScopePerson    Scope = "person"
	ScopeGuest     Scope = "guest"
)

// ParamSpec is one declared parameter. Providers map these onto their own wire
// shape, so every backend offers the model the same tool (SPEC §12).
type ParamSpec struct {
	Name        string
	Type        string
	Description string
	Required    bool
	Enum        []string
	Items       string
}

// ToolSpec is the generated policy for one tool.
type ToolSpec struct {
	Name        string
	Description string

	// ModelDescription is what the model is told, which is not what the docs
	// show: a slow tool carries a latency hint it has to act on (SPEC §14).
	ModelDescription string

	// Params are what the tool's executor declares and receives. ModelParams
	// are what the model is offered, which adds the arguments the
	// orchestrator acts on and strips before the executor sees the call: the
	// acknowledgement on a slow tool, the nonce on a confirmable one.
	Params               []ParamSpec
	ModelParams          []ParamSpec
	OnInterrupt          InterruptPolicy
	Scope                Scope
	Timeout              time.Duration
	RequiresConfirmation bool
	Slow                 bool
	UnknownSpeaker       string

	// ConfirmWhen holds the calls whose arguments match any entry for the
	// person's yes, when the tool as a whole needs none (ADR-0038).
	ConfirmWhen []ConfirmRule
}

// ConfirmRule is one confirm_when entry. A call matches when its arguments
// carry every value in Args and, when TargetClass names any, what it acts
// on has one of those classes (ADR-0041).
type ConfirmRule struct {
	Args        map[string]string
	TargetClass []string
}

`)
	b.WriteString("// Specs is every declared tool, keyed by name.\nvar Specs = map[string]ToolSpec{\n")
	for _, key := range sortedKeys(tools) {
		t := tools[key]
		b.WriteString(fmt.Sprintf("\t%q: {\n", t.Name))
		b.WriteString(fmt.Sprintf("\t\tName: %q,\n", t.Name))
		b.WriteString(fmt.Sprintf("\t\tDescription: %q,\n", t.Description))
		b.WriteString(fmt.Sprintf("\t\tModelDescription: %q,\n", describe(t)))
		b.WriteString(renderParams("Params", t.Params))
		b.WriteString(renderParams("ModelParams", offered(t)))
		b.WriteString(fmt.Sprintf("\t\tOnInterrupt: %q,\n", t.OnInterrupt))
		b.WriteString(fmt.Sprintf("\t\tScope: %q,\n", t.Scope))
		b.WriteString(fmt.Sprintf("\t\tTimeout: %d * time.Millisecond,\n", t.TimeoutMS))
		b.WriteString(fmt.Sprintf("\t\tRequiresConfirmation: %t,\n", t.RequiresConfirmation))
		b.WriteString(fmt.Sprintf("\t\tSlow: %t,\n", t.Latency == "slow"))
		if t.UnknownSpeaker != "" {
			b.WriteString(fmt.Sprintf("\t\tUnknownSpeaker: %q,\n", t.UnknownSpeaker))
		}
		b.WriteString(renderConfirmWhen(t.ConfirmWhen))
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func renderParams(field string, params []Param) string {
	if len(params) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("\t\t" + field + ": []ParamSpec{\n")
	for _, p := range params {
		b.WriteString(fmt.Sprintf("\t\t\t{Name: %q, Type: %q, Description: %q, Required: %t",
			p.Name, p.Type, p.Description, p.Required))
		if len(p.Enum) > 0 {
			quoted := make([]string, len(p.Enum))
			for i, e := range p.Enum {
				quoted[i] = fmt.Sprintf("%q", e)
			}
			b.WriteString(fmt.Sprintf(", Enum: []string{%s}", strings.Join(quoted, ", ")))
		}
		if p.Items != "" {
			b.WriteString(fmt.Sprintf(", Items: %q", p.Items))
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t\t},\n")
	return b.String()
}

func renderConfirmWhen(when []ConfirmRule) string {
	if len(when) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("\t\tConfirmWhen: []ConfirmRule{\n")
	for _, r := range when {
		pairs := make([]string, 0, len(r.Args))
		for _, k := range sortedKeys(r.Args) {
			pairs = append(pairs, fmt.Sprintf("%q: %q", k, r.Args[k]))
		}
		b.WriteString(fmt.Sprintf("\t\t\t{Args: map[string]string{%s}", strings.Join(pairs, ", ")))
		if len(r.TargetClass) > 0 {
			quoted := make([]string, len(r.TargetClass))
			for i, c := range r.TargetClass {
				quoted[i] = fmt.Sprintf("%q", c)
			}
			b.WriteString(fmt.Sprintf(", TargetClass: []string{%s}", strings.Join(quoted, ", ")))
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t\t},\n")
	return b.String()
}

func renderEventsGo(events map[string]Event) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package journal\n\n")
	b.WriteString(`// Kind identifies a journal event type. The journal is the source of truth,
// so every write is validated against this set (SPEC §8).
type Kind string

// Actor is the supervisor child that produced an event (SPEC §4).
type Actor string

`)
	b.WriteString("const (\n")
	for _, key := range sortedKeys(events) {
		e := events[key]
		b.WriteString(fmt.Sprintf("\t// %s\n", e.Description))
		b.WriteString(fmt.Sprintf("\tKind%s Kind = %q\n", goName(e.Name), e.Name))
	}
	b.WriteString(")\n\n")

	b.WriteString("// EventMeta is generated metadata used by the journal and the harvester.\ntype EventMeta struct {\n\tActor Actor\n\tHasAudio bool\n\tTrainingSignal bool\n\tSpeculative bool\n\tRequiresVersions bool\n\tRequiredFields []string\n}\n\n")
	b.WriteString("// Meta describes every known event kind.\nvar Meta = map[Kind]EventMeta{\n")
	for _, key := range sortedKeys(events) {
		e := events[key]
		var req []string
		for _, f := range e.Fields {
			if f.Required {
				req = append(req, fmt.Sprintf("%q", f.Name))
			}
		}
		b.WriteString(fmt.Sprintf("\tKind%s: {Actor: %q, HasAudio: %t, TrainingSignal: %t, Speculative: %t, RequiresVersions: %t, RequiredFields: []string{%s}},\n",
			goName(e.Name), e.Actor, e.HasAudio, e.TrainingSignal, e.Speculative, e.RequiresVersion, strings.Join(req, ", ")))
	}
	b.WriteString("}\n\n")

	b.WriteString("// AllKinds lets replay assert exhaustive handling.\nvar AllKinds = []Kind{\n")
	for _, key := range sortedKeys(events) {
		b.WriteString(fmt.Sprintf("\tKind%s,\n", goName(events[key].Name)))
	}
	b.WriteString("}\n")
	return b.String()
}

func renderToolDocs(tools map[string]Tool) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by schemagen from schema/tool.cue. DO NOT EDIT. -->\n\n")
	b.WriteString("# Tool registry reference\n\nSee [SPEC §6](../SPEC.md). Policy is enforced by the orchestrator from these same declarations.\n\n")
	b.WriteString("| Tool | Interrupt | Scope | Timeout | Confirm | Latency |\n|---|---|---|---|---|---|\n")
	for _, key := range sortedKeys(tools) {
		t := tools[key]
		confirm := "no"
		switch {
		case t.RequiresConfirmation:
			confirm = "**yes**"
		case len(t.ConfirmWhen) > 0:
			confirm = "**some calls**"
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %dms | %s | %s |\n",
			t.Name, t.OnInterrupt, t.Scope, t.TimeoutMS, confirm, t.Latency))
	}
	b.WriteString("\n")
	for _, key := range sortedKeys(tools) {
		t := tools[key]
		b.WriteString(fmt.Sprintf("## `%s`\n\n%s\n\n", t.Name, t.Description))
		if t.UnknownSpeaker != "" {
			b.WriteString(fmt.Sprintf("Unknown speaker: `%s`.\n\n", t.UnknownSpeaker))
		}
		b.WriteString(renderConfirmDocs(t.ConfirmWhen))
		b.WriteString(renderParamTable("Parameter", offered(t), "No parameters."))
	}
	return b.String()
}

// renderConfirmDocs lists the calls a tool holds for the person's yes, one
// per line, as the arguments that match.
func renderConfirmDocs(when []ConfirmRule) string {
	if len(when) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("Needs the person's yes when called with:\n\n")
	for _, r := range when {
		pairs := make([]string, 0, len(r.Args))
		for _, k := range sortedKeys(r.Args) {
			pairs = append(pairs, fmt.Sprintf("`%s` `%s`", k, r.Args[k]))
		}
		line := "- " + strings.Join(pairs, ", ")
		if len(r.TargetClass) > 0 {
			classes := make([]string, len(r.TargetClass))
			for i, c := range r.TargetClass {
				classes[i] = "`" + c + "`"
			}
			line += ", on a target of class " + strings.Join(classes, ", ")
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("\n")
	return b.String()
}

func renderEventDocs(events map[string]Event) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by schemagen from schema/event.cue. DO NOT EDIT. -->\n\n")
	b.WriteString("# Event taxonomy reference\n\nSee [SPEC §8](../SPEC.md). The journal is the runtime's source of truth.\n\n")
	b.WriteString("| Event | Actor | Audio | Training signal | Description |\n|---|---|---|---|---|\n")
	for _, key := range sortedKeys(events) {
		e := events[key]
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s |\n",
			e.Name, e.Actor, yn(e.HasAudio), yn(e.TrainingSignal), e.Description))
	}
	b.WriteString("\n")
	for _, key := range sortedKeys(events) {
		e := events[key]
		b.WriteString(fmt.Sprintf("## `%s`\n\n%s\n\n", e.Name, e.Description))
		// Named as in schema/event.cue, so a reader can find the declaration.
		b.WriteString(fmt.Sprintf("Actor: `%s`. `has_audio`: %s. `training_signal`: %s. `speculative`: %s. `requires_versions`: %s.\n\n",
			e.Actor, yesNo(e.HasAudio), yesNo(e.TrainingSignal), yesNo(e.Speculative), yesNo(e.RequiresVersion)))
		b.WriteString(renderParamTable("Field", e.Fields, "No fields."))
	}
	return b.String()
}

// renderParamTable is shared by tools and events so their docs cannot drift
// apart in shape. An empty list is stated, not left as a blank section.
func renderParamTable(column string, params []Param, none string) string {
	if len(params) == 0 {
		return none + "\n\n"
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("| %s | Type | Required | Description |\n|---|---|---|---|\n", column))
	for _, p := range params {
		req := ""
		if p.Required {
			req = "yes"
		}
		desc := p.Description
		if len(p.Enum) > 0 {
			desc += fmt.Sprintf(" One of: `%s`.", strings.Join(p.Enum, "`, `"))
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", p.Name, p.Type, req, desc))
	}
	b.WriteString("\n")
	return b.String()
}

// yn is for table cells, where a blank reads better than a column of "no".
func yn(b bool) string {
	if b {
		return "yes"
	}
	return ""
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func goName(s string) string {
	var b strings.Builder
	for part := range strings.SplitSeq(strings.ReplaceAll(s, ".", "_"), "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
